server:
  port: 8081
  servlet:
    context-path: /ws-oshs
    application-display-name: oshs
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://vm-mgsn-as1-dev.ursip.ru:5432/mgsn
    username: postgres
    password: qwerty123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 20
  jpa:
    show-sql: true
#    generate-ddl: true
    properties:
      hibernate:
        default_schema: oshs
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    ru.ursip.webservice.mgsn.oshs: DEBUG
    org.springframework.web: DEBUG
  file: logs/oshs.log